Repository codestates-seb/seb40_main_018, pull requests merged in 2022-12, with the labels that each got.

#125 [BE] fix : Member map 요청에 맞게 수정
  server/danim/src/main/java/project/danim/member/controller/MemberController.java
  server/danim/src/main/java/project/danim/member/dto/MemberResponseForMap.java
  server/danim/src/main/java/project/danim/member/service/MemberQueries.java
Labels: BE

#136 [BE] 부수적인 부분 수정
  server/danim/src/main/java/project/danim/S3/S3Controller.java
  server/danim/src/main/java/project/danim/bucket/controller/BucketController.java
  server/danim/src/main/java/project/danim/bucket/domain/Bucket.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketResponseDto.java
  server/danim/src/main/java/project/danim/bucket/service/BucketService.java
  server/danim/src/main/java/project/danim/check/controller/CheckController.java
  server/danim/src/main/java/project/danim/check/domain/Check.java
  server/danim/src/main/java/project/danim/check/dto/CheckResponseDto.java
  server/danim/src/main/java/project/danim/check/service/CheckService.java
  server/danim/src/main/java/project/danim/reply/controller/ReplyController.java
  server/danim/src/main/java/project/danim/reply/domain/Reply.java
  server/danim/src/main/java/project/danim/reply/dto/ReplyResponseDto.java
  server/danim/src/main/java/project/danim/reply/service/ReplyService.java
  server/danim/src/main/java/project/danim/tag/service/TagService.java
Labels: feature, BE 김은진, chore

#135 [BE] diary 리스폰스 수정
  server/danim/src/main/java/project/danim/diary/controller/DiaryController.java
  server/danim/src/main/java/project/danim/diary/dto/DiaryResponseDto.java
  server/danim/src/main/java/project/danim/diary/mapper/DiaryMapper.java
  server/danim/src/main/java/project/danim/diary/service/DiaryService.java
  server/danim/src/main/java/project/danim/member/dto/MemberResponseForProfileDiaries.java
  server/danim/src/main/java/project/danim/security/config/SecurityConfig.java
Labels: BE

#140 [BE] Diary Update, Delete 수정 & Tag Create, Update, Delete 추가
  server/danim/src/main/java/project/danim/diary/controller/DiaryController.java
  server/danim/src/main/java/project/danim/diary/domain/Diary.java
  server/danim/src/main/java/project/danim/diary/dto/DiaryPatchDto.java
  server/danim/src/main/java/project/danim/diary/dto/DiaryPostDto.java
  server/danim/src/main/java/project/danim/diary/dto/DiaryResponseDto.java
  server/danim/src/main/java/project/danim/diary/mapper/DiaryMapper.java
  server/danim/src/main/java/project/danim/diary/service/DiaryService.java
  server/danim/src/main/java/project/danim/exeption/BusinessLogicException.java
  server/danim/src/main/java/project/danim/security/config/SecurityConfig.java
  server/danim/src/main/java/project/danim/tag/controller/TagController.java
  server/danim/src/main/java/project/danim/tag/domain/Tag.java
  server/danim/src/main/java/project/danim/tag/dto/TagResponseDto.java
  server/danim/src/main/java/project/danim/tag/repository/TagRepository.java
  server/danim/src/main/java/project/danim/tag/service/TagService.java
Labels: BE

#142 [BE] fix : Diary Image 작업
  server/danim/src/main/java/project/danim/S3/S3Controller.java
  server/danim/src/main/java/project/danim/S3/S3Service.java
  server/danim/src/main/java/project/danim/diary/controller/DiaryController.java
  server/danim/src/main/java/project/danim/diary/domain/Diary.java
  server/danim/src/main/java/project/danim/diary/dto/DiaryResponseDto.java
  server/danim/src/main/java/project/danim/diary/mapper/DiaryMapper.java
  server/danim/src/main/java/project/danim/diary/service/DiaryService.java
Labels: BE

#145 [BE] fix : Diary Image 일부 수정, Member Profile Image 추가
  server/danim/src/main/java/project/danim/S3/S3Service.java
  server/danim/src/main/java/project/danim/diary/service/DiaryService.java
  server/danim/src/main/java/project/danim/member/controller/MemberController.java
  server/danim/src/main/java/project/danim/member/dto/MemberProfilePatchForm.java
  server/danim/src/main/java/project/danim/member/service/MemberService.java
Labels: BE

#146 Fe user edit
  client/src/components/Main/MainTab.js
  client/src/pages/MainPage.js
  client/src/pages/MyPage/MyPage.js
Labels: FE 방혜민, FE

#158 [BE] fix : Tag 검색 및 Main 페이지 응답 수정
  server/danim/src/main/java/project/danim/diary/dto/DiaryResponseDtoForCard.java
  server/danim/src/main/java/project/danim/diary/service/DiaryService.java
  server/danim/src/main/java/project/danim/member/service/MemberService.java
  server/danim/src/main/java/project/danim/tag/dto/TagDiaryResponseDto.java
  server/danim/src/main/java/project/danim/tag/service/TagService.java
Labels: BE

#159 [BE] fix : Tag 검색 및 Main 페이지 응답 수정
  server/danim/src/main/java/project/danim/diary/dto/DiaryResponseDtoForCard.java
  server/danim/src/main/java/project/danim/tag/dto/TagDiaryResponseDto.java
Labels: BE
