Repository codestates-seb/seb40_main_018, pull requests merged in 2022-11, with the labels that each got.

#11 [BE] 기본 디렉토리 구성 / 공동 사용 reponseDto, exeption 추가
  server/danim/src/main/java/project/danim/bucket/controller/BucketController.java
  server/danim/src/main/java/project/danim/bucket/domain/Bucket.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketDeleteDto.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketPatchDto.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketPostDto.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketResponseDto.java
  server/danim/src/main/java/project/danim/bucket/mapper/BucketMapper.java
  server/danim/src/main/java/project/danim/bucket/repository/BucketRepository.java
  server/danim/src/main/java/project/danim/bucket/service/BucketService.java
  server/danim/src/main/java/project/danim/check/controller/CheckController.java
  server/danim/src/main/java/project/danim/check/domain/Check.java
  server/danim/src/main/java/project/danim/check/dto/CheckDeleteDto.java
  server/danim/src/main/java/project/danim/check/dto/CheckPatchDto.java
  server/danim/src/main/java/project/danim/check/dto/CheckPostDto.java
  server/danim/src/main/java/project/danim/check/dto/CheckResponseDto.java
  server/danim/src/main/java/project/danim/check/mapper/CheckMapper.java
  server/danim/src/main/java/project/danim/check/repository/CheckRepository.java
  server/danim/src/main/java/project/danim/check/service/CheckService.java
  server/danim/src/main/java/project/danim/exeption/BusinessLogicException.java
  server/danim/src/main/java/project/danim/exeption/ErrorResponse.java
  server/danim/src/main/java/project/danim/exeption/ExceptionCode.java
  server/danim/src/main/java/project/danim/exeption/GlobalException.java
  server/danim/src/main/java/project/danim/response/MultiResponseDto.java
  server/danim/src/main/java/project/danim/response/PageInfo.java
  server/danim/src/main/java/project/danim/response/SingleResponseDto.java
Labels: feature

#12 💄 design: add svg
  client/src/images/Danim - MarkMaker Logo.png
  client/src/images/Danim - MarkMaker Logo.svg
Labels: FE 김예린

#28 [BE] 체크리스트, 버킷리스트 구현 완료
  server/danim/src/main/java/project/danim/bucket/controller/BucketController.java
  server/danim/src/main/java/project/danim/bucket/domain/Bucket.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketDeleteDto.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketPatchDto.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketPostDto.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketResponseDto.java
  server/danim/src/main/java/project/danim/bucket/mapper/BucketMapper.java
  server/danim/src/main/java/project/danim/bucket/repository/BucketRepository.java
  server/danim/src/main/java/project/danim/bucket/service/BucketService.java
  server/danim/src/main/java/project/danim/check/controller/CheckController.java
  server/danim/src/main/java/project/danim/check/domain/Check.java
  server/danim/src/main/java/project/danim/check/dto/CheckDeleteDto.java
  server/danim/src/main/java/project/danim/check/dto/CheckPatchDto.java
  server/danim/src/main/java/project/danim/check/dto/CheckPostDto.java
  server/danim/src/main/java/project/danim/check/dto/CheckResponseDto.java
  server/danim/src/main/java/project/danim/check/mapper/CheckMapper.java
  server/danim/src/main/java/project/danim/check/repository/CheckRepository.java
  server/danim/src/main/java/project/danim/check/service/CheckService.java
  server/danim/src/main/java/project/danim/exeption/ExceptionCode.java
  server/danim/src/main/java/project/danim/image/controller/ImageController.java
Labels: feature, BE 김은진

#31 feat :헤더 & 헤더 모달 & 로그아웃 모달
  .github/ISSUE_TEMPLATE/feature.md
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Header/Header.js
  client/src/components/Header/LoginHeader.js
  client/src/components/Modal/HeaderModal.js
  client/src/images/DanimLogo.PNG
  client/src/images/user.png
  client/src/pages/Main.js
  client/src/pages/MainPage.js
  server/danim/src/main/java/project/danim/bucket/controller/BucketController.java
  server/danim/src/main/java/project/danim/bucket/controller/BucketListController.java
  server/danim/src/main/java/project/danim/bucket/domain/Bucket.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketDeleteDto.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketPatchDto.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketPostDto.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketResponseDto.java
  server/danim/src/main/java/project/danim/bucket/repository/BucketRepository.java
  server/danim/src/main/java/project/danim/bucket/service/BucketService.java
  server/danim/src/main/java/project/danim/check/controller/CheckController.java
  server/danim/src/main/java/project/danim/check/controller/ChecklistController.java
  server/danim/src/main/java/project/danim/check/domain/Check.java
  server/danim/src/main/java/project/danim/check/dto/CheckDeleteDto.java
  server/danim/src/main/java/project/danim/check/dto/CheckPatchDto.java
  server/danim/src/main/java/project/danim/check/dto/CheckPostDto.java
  server/danim/src/main/java/project/danim/check/dto/CheckResponseDto.java
  server/danim/src/main/java/project/danim/check/repository/CheckRepository.java
  server/danim/src/main/java/project/danim/check/service/CheckService.java
  server/danim/src/main/java/project/danim/exeption/BusinessLogicException.java
  server/danim/src/main/java/project/danim/exeption/ErrorResponse.java
  server/danim/src/main/java/project/danim/exeption/ExceptionCode.java
  server/danim/src/main/java/project/danim/exeption/GlobalException.java
  server/danim/src/main/java/project/danim/image/controller/ImageController.java
  server/danim/src/main/java/project/danim/response/MultiResponseDto.java
  server/danim/src/main/java/project/danim/response/PageInfo.java
  server/danim/src/main/java/project/danim/response/SingleResponseDto.java
Labels: FE 김예린, FE

#33 [front] Input Component 디자인
  client/src/components/Input/CheckListInput.js
  client/src/components/Input/ShortInput.js
  client/src/style/GlobalStyle.js
Labels: FE 김은서, FE

#37 [FE] Button /태그는 따로 올리겠습니다
  client/src/components/Button/DarkLineButton.js
  client/src/components/Button/DarkMintButton.js
  client/src/components/Button/MintButton.js
  client/src/components/Button/MintLineButton.js
  client/src/components/Button/index.js
Labels: FE 방혜민, FE

#40 [FE] Card, Tag 컴포넌트
  client/src/components/Card.js/MintCard.js
  client/src/components/Tag.js/DarkMintTag.js
  client/src/images/DanimLogo.PNG
  client/src/images/DanimLogo.png
Labels: FE 방혜민, FE

#41 Add: Swagger 세팅 추가
  server/danim/build.gradle
  server/danim/src/main/java/SwaggerConfig.java
Labels: BE 김은진, chore

#44 Chore: config 경로 수정
  server/danim/src/main/java/project/danim/SwaggerConfig.java
Labels: BE 김은진, chore

#45 ✨ feat: 취소, 삭제 모달 창 구현
  client/package-lock.json
  client/package.json
  client/src/components/Button/MintButton.js
  client/src/components/CheckList-BucketList/BucketList.js
  client/src/components/CheckList-BucketList/CheckList.js
  client/src/components/CheckList-BucketList/Input.js
  client/src/components/CheckList-BucketList/MyListButton.js
  client/src/components/Input/CheckListInput.js
  client/src/components/Input/ShortInput.js
  client/src/components/Login-Logout-Signup/SignupForm.js
  client/src/components/Modal/BaseModal.js
  client/src/components/Modal/BucketList/BucketInput.js
  client/src/components/Modal/BucketList/BucketList.js
  client/src/components/Modal/BucketList/BucketListModal.js
  client/src/components/Modal/CancelModal.js
  client/src/components/Modal/CheckList/CheckInput.js
  client/src/components/Modal/CheckList/CheckList.js
  client/src/components/Modal/CheckList/CheckListModal.js
  client/src/components/Modal/DeleteModal.js
  client/src/components/Modal/HeaderModal.js
  client/src/pages/MainPage.js
  client/src/pages/MyList.js
Labels: FE 김예린, FE

#47 Fe writepage
  .vscode/settings.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Header/LoginHeader.js
  client/src/index.css
  client/src/pages/Diary.js
  client/src/pages/Diary/Diary.js
  client/src/pages/Diary/DiaryButton.js
  client/src/pages/Diary/DiaryHashtag.js
  client/src/pages/Diary/DiaryImg.js
  client/src/pages/Diary/DiaryPlace.js
  client/src/pages/Diary/DiaryPrice.js
  client/src/pages/Diary/DiaryText.js
  client/src/pages/Diary/DiaryTitle.js
  client/src/pages/Diary/tag.css
  client/src/style/font/SSShinb7Regular.ttf
  client/src/style/font/SSShinb7Regular_otf.otf
Labels: FE 김은서, FE

#48 [Front] 상세페이지 디자인
  client/src/components/Input/CheckListInput.js
  client/src/pages/Detail.js
  client/src/style/GlobalStyle.js
Labels: FE 김은서, FE

#50 ⚡️ fix: 체크리스트, 버킷리스트 모달 기능 구현 완료
  client/package-lock.json
  client/package.json
  client/src/components/CheckList-BucketList/BucketList.js
  client/src/components/CheckList-BucketList/CheckList.js
  client/src/components/CheckList-BucketList/Input.js
  client/src/components/CheckList-BucketList/MyListButton.js
  client/src/components/Header/Header.js
  client/src/components/Header/LoginHeader.js
  client/src/components/Login-Logout-Signup/LoginForm.js
  client/src/components/Login-Logout-Signup/SignupForm.js
  client/src/components/Modal/BaseModal.js
  client/src/components/Modal/BucketList/BucketInput.js
  client/src/components/Modal/BucketList/BucketList.js
  client/src/components/Modal/BucketList/BucketListModal.js
  client/src/components/Modal/CheckList-BucketList/MyListButton.js
  client/src/components/Modal/CheckList/CheckInput.js
  client/src/components/Modal/CheckList/CheckList.js
  client/src/components/Modal/CheckList/CheckListModal.js
  client/src/components/Modal/HeaderModal.js
  client/src/pages/Diary/Diary.js
  client/src/pages/MainPage.js
  client/src/pages/MyList.js
Labels: FE 김예린, FE

#51 [front] feat : 다이어리 수정페이지 디자인
  client/src/App.js
  client/src/pages/DiaryEdit.js
  client/src/pages/DiaryEdit/DiaryEdit.js
  client/src/pages/DiaryEdit/DiaryEditHashtag.js
  client/src/pages/DiaryEdit/DiaryEditImg.js
  client/src/pages/DiaryEdit/DiaryEditPlace.js
  client/src/pages/DiaryEdit/DiaryEditPrice.js
  client/src/pages/DiaryEdit/DiaryEditText.js
  client/src/pages/DiaryEdit/DiaryEditTitle.js
Labels: FE 김은서, FE

#52 [front] 사진업로드 max 10장, 랜덤질문 max 3번 구현
  client/src/pages/Diary/DiaryImg.js
  client/src/pages/Diary/DiaryText.js
  client/src/pages/DiaryEdit/DiaryEdit.js
  client/src/pages/DiaryEdit/DiaryEditImg.js
Labels: FE 김은서, FE

#53 [front]design : MyPage 디자인
  client/src/App.js
  client/src/images/southKoreaHigh.svg
  client/src/pages/MyPage.js
  client/src/pages/MyPage/MapIcon.js
  client/src/pages/MyPage/MapageCard.js
  client/src/pages/MyPage/MyPage.js
  client/src/pages/MyPage/MyPageSearch.js
Labels: FE 김은서, FE

#55 ✨ 마이리스트 페이지 구현
  client/src/Filter/PriceFilter.js
  client/src/components/Button/DarkMintButton.js
  client/src/components/Input/ShortInput.js
  client/src/components/Login-Logout-Signup/LoginForm.js
  client/src/components/Login-Logout-Signup/SignupForm.js
  client/src/components/Modal/BucketList/BucketInput.js
  client/src/components/Modal/BucketList/BucketList.js
  client/src/components/Modal/BucketList/BucketListModal.js
  client/src/components/Modal/CheckList-BucketList/MyListButton.js
  client/src/components/Modal/CheckList/CheckInput.js
  client/src/components/Modal/CheckList/CheckList.js
  client/src/components/Modal/CheckList/CheckListModal.js
  client/src/components/Modal/HeaderModal.js
  client/src/pages/MyList.js
  client/src/pages/MyPage/MyPage.js
Labels: FE 김예린, FE

#57 ✨ feat : 상세페이지 수정 삭제 버튼 구현
  client/src/pages/Detail.js
Labels: FE 김은서, FE

#62 [BE]add : 멤버 도메인 회원가입과 본인 프로파일 가져오기
  server/danim/src/main/java/project/danim/DanimApplication.java
  server/danim/src/main/java/project/danim/SecurityConfig.java
  server/danim/src/main/java/project/danim/exeption/ResourceNotFoundException.java
  server/danim/src/main/java/project/danim/member/adapter/in/web/MemberController.java
  server/danim/src/main/java/project/danim/member/adapter/in/web/MemberCreateForm.java
  server/danim/src/main/java/project/danim/member/adapter/out/persistence/MemberRepository.java
  server/danim/src/main/java/project/danim/member/adapter/out/persistence/MemberRepositoryPersistenceAdapter.java
  server/danim/src/main/java/project/danim/member/application/port/in/CreateMemberUserCase.java
  server/danim/src/main/java/project/danim/member/application/port/in/MemberQueriesUseCase.java
  server/danim/src/main/java/project/danim/member/application/port/in/request/CreateMemberCommand.java
  server/danim/src/main/java/project/danim/member/application/port/in/response/MemberResponseForProfile.java
  server/danim/src/main/java/project/danim/member/application/port/out/MemberRepositoryPort.java
  server/danim/src/main/java/project/danim/member/application/service/MemberQueries.java
  server/danim/src/main/java/project/danim/member/application/service/MemberService.java
  server/danim/src/main/java/project/danim/member/controller/MemberController.java
  server/danim/src/main/java/project/danim/member/domain/Member.java
  server/danim/src/main/java/project/danim/member/domain/MemberExistsException.java
  server/danim/src/main/java/project/danim/member/domain/MemberNotFoundException.java
Labels: BE 임원용

#61 🎨 fix: 모달 창 구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Filter/PriceFilter.js
  client/src/components/Comment/CommentTool.js
  client/src/components/Comment/Markdown.js
  client/src/images/user.png
  client/src/index.js
  client/src/pages/Detail/Comment.js
  client/src/pages/Detail/Detail.js
  client/src/pages/Detail/DetailCopy.js
  client/src/pages/Diary/DiaryPlace.js
  client/src/redux/comment.js
  client/src/redux/store.js
Labels: FE 김예린, FE

#70 Fe mylist
  client/data/todos.json
  client/package.json
  client/src/Filter/PriceFilter.js
  client/src/components/Main/MainTab.js
  client/src/components/Modal/CheckList/CheckList.js
  client/src/pages/Detail/Comment.js
  client/src/pages/MainPage.js
Labels: FE 김예린, FE

#72 ✨ feat :이미지 통신 준비
  client/data/comment.json
  client/data/diary.json
  client/data/image.json
  client/src/pages/Detail/Comment.js
  client/src/pages/Detail/Detail.js
  client/src/pages/Diary/Diary.js
  client/src/pages/Diary/DiaryImg.js
  client/src/pages/Diary/DiaryPlace.js
  client/src/pages/Diary/DiaryPrice.js
  client/src/pages/Diary/DiaryTitle.js
  client/src/pages/MainPage.js
Labels: FE 김은서, FE

#80 ✨ setupProxy 파일 추가
  client/.eslintrc.json
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/Filter/PriceFilter.js
  client/src/components/Main/MainTab.js
  client/src/setupProxy.js
Labels: FE 김예린, FE

#83 [BE] fix : Security Config 수정
  server/danim/src/main/java/project/danim/security/config/SecurityConfig.java
  server/danim/src/main/java/project/danim/security/jwt/JwtAuthenticationFilter.java
Labels: BE

#84 [FE] user edit data까지 완료
  client/data/userProfile.json
  client/src/components/UserEdit/UserEdit.js
  client/src/images/user.png
  client/src/pages/MyPage/MyPage.js
Labels: FE 방혜민, FE

#92 [BE] 댓글 CRUD 구현 완료
  .gitignore
  server/danim/src/main/java/project/danim/AmazonConfig.java
  server/danim/src/main/java/project/danim/bucket/controller/BucketController.java
  server/danim/src/main/java/project/danim/bucket/domain/Bucket.java
  server/danim/src/main/java/project/danim/bucket/dto/BucketResponseDto.java
  server/danim/src/main/java/project/danim/check/domain/Check.java
  server/danim/src/main/java/project/danim/check/dto/CheckResponseDto.java
  server/danim/src/main/java/project/danim/diary/domain/Diary.java
  server/danim/src/main/java/project/danim/diary/repository/DiaryRepository.java
  server/danim/src/main/java/project/danim/image/AwsS3Controller.java
  server/danim/src/main/java/project/danim/image/FileStore.java
  server/danim/src/main/java/project/danim/image/controller/DiaryAddForm.java
  server/danim/src/main/java/project/danim/image/controller/ImageController.java
  server/danim/src/main/java/project/danim/image/controller/ImageForm.java
  server/danim/src/main/java/project/danim/image/domain/Attachment.java
  server/danim/src/main/java/project/danim/image/domain/Image.java
  server/danim/src/main/java/project/danim/image/domain/ImagePath.java
  server/danim/src/main/java/project/danim/image/dto/ImageDeleteDto.java
  server/danim/src/main/java/project/danim/image/dto/ImagePatchDto.java
  server/danim/src/main/java/project/danim/image/dto/ImagePostDto.java
  server/danim/src/main/java/project/danim/image/dto/ImageResponseDto.java
  server/danim/src/main/java/project/danim/image/file/FileStore.java
  server/danim/src/main/java/project/danim/image/repository/AttachmentType.java
  server/danim/src/main/java/project/danim/image/repository/ImageRepository.java
  server/danim/src/main/java/project/danim/image/service/ImageService.java
  server/danim/src/main/java/project/danim/image/service/ImageServiceImpl.java
  server/danim/src/main/java/project/danim/reply/controller/ReplyController.java
  server/danim/src/main/java/project/danim/reply/domain/Reply.java
  server/danim/src/main/java/project/danim/reply/dto/ReplyDeleteDto.java
  server/danim/src/main/java/project/danim/reply/dto/ReplyPatchDto.java
  server/danim/src/main/java/project/danim/reply/dto/ReplyPostDto.java
  server/danim/src/main/java/project/danim/reply/dto/ReplyResponseDto.java
  server/danim/src/main/java/project/danim/reply/repository/ReplyRepository.java
  server/danim/src/main/java/project/danim/reply/service/ReplyService.java
  server/danim/src/main/resources/application.properties
Labels: feature, BE 김은진

#93 [BE] 설정 및 경로 변경
  server/danim/src/main/generated/project/danim/diary/mapper/DiaryMapperImpl.java
  server/danim/src/main/java/project/danim/AmazonConfig.java
  server/danim/src/main/java/project/danim/SecurityConfig.java
  server/danim/src/main/java/project/danim/config/AmazonConfig.java
  server/danim/src/main/java/project/danim/diary/repository/DiaryRepository.java
  server/danim/src/main/java/project/danim/image/AwsS3Controller.java
  server/danim/src/main/java/project/danim/image/FileStore.java
Labels: BE 김은진, chore

#95 Add: tag CRUD 구현 완료
  server/danim/src/main/java/project/danim/diary/domain/Diary.java
  server/danim/src/main/java/project/danim/tag/controller/TagController.java
  server/danim/src/main/java/project/danim/tag/domain/Tag.java
  server/danim/src/main/java/project/danim/tag/dto/TagDeleteDto.java
  server/danim/src/main/java/project/danim/tag/dto/TagPatchDto.java
  server/danim/src/main/java/project/danim/tag/dto/TagPostDto.java
  server/danim/src/main/java/project/danim/tag/dto/TagResponseDto.java
  server/danim/src/main/java/project/danim/tag/repository/TagRepository.java
  server/danim/src/main/java/project/danim/tag/service/TagService.java
Labels: feature, BE 김은진

#98 [FE] main page 구성
  client/src/App.js
  client/src/components/Main/Card.js
  client/src/components/Main/MainTab.js
  client/src/components/UserEdit/UserEdit.js
Labels: FE 방혜민, FE

#100 feat: 로딩이미지&스켈레톤 적용 완료
  client/.env
  client/data/comment.json
  client/data/diary.json
  client/package-lock.json
  client/package.json
  client/src/components/BucketList/BucketInput.js
  client/src/components/BucketList/BucketList.js
  client/src/components/BucketList/BucketListModal.js
  client/src/components/CheckList/CheckInput.js
  client/src/components/CheckList/CheckList.js
  client/src/components/CheckList/CheckListModal.js
  client/src/components/Header/Header.js
  client/src/components/Main/Card.js
  client/src/components/Main/MainTab.js
  client/src/components/Main/PriceFilter.js
  client/src/components/Skeleton/SkeletonCard.js
  client/src/components/Skeleton/SkeletonComment.js
  client/src/components/Skeleton/SkeletonDiary.js
  client/src/components/Skeleton/SkeletonUser.js
  client/src/components/UserEdit/UserEdit.js
  client/src/pages/Detail/Comment.js
  client/src/pages/Diary/Diary.js
  client/src/pages/DiaryEdit/DiaryEdit.js
  client/src/pages/Loading.js
  client/src/pages/MainPage.js
  client/src/pages/MyList.js
  client/src/pages/MyPage/MyPage.js
  client/src/pages/MyPage/MyPageCard.js
  client/src/pages/MyPage/MyPageSearch.js
  client/src/setupProxy.js
Labels: FE 김예린, FE

#106 fix : aws 설정 수정
  server/danim/src/main/resources/application.yml
Labels: BE 유현아

#115 ✨ 태그검색 구현중 (예린님을 위한 pr)
  client/data/diary.json
  client/src/components/Main/Card.js
  client/src/components/Main/MainTab.js
  client/src/pages/MainPage.js
  client/src/pages/MyPage/MyPageCard.js
Labels: FE 방혜민, FE

#117 [BE] fix : member, diary 기능 수정 및 추가
  server/danim/src/main/java/project/danim/diary/controller/DiaryController.java
  server/danim/src/main/java/project/danim/diary/domain/Diary.java
  server/danim/src/main/java/project/danim/diary/dto/DiaryPostDto.java
  server/danim/src/main/java/project/danim/diary/dto/DiaryResponseDto.java
  server/danim/src/main/java/project/danim/diary/mapper/DiaryMapper.java
  server/danim/src/main/java/project/danim/diary/repository/DiaryRepository.java
  server/danim/src/main/java/project/danim/diary/service/DiaryService.java
  server/danim/src/main/java/project/danim/exeption/ExceptionCode.java
  server/danim/src/main/java/project/danim/likes/controller/LikesController.java
  server/danim/src/main/java/project/danim/likes/domain/Likes.java
  server/danim/src/main/java/project/danim/likes/repository/LikesRepository.java
  server/danim/src/main/java/project/danim/likes/service/LikesService.java
  server/danim/src/main/java/project/danim/member/controller/MemberController.java
  server/danim/src/main/java/project/danim/member/domain/Member.java
  server/danim/src/main/java/project/danim/member/dto/MemberResponseForProfileDiaries.java
  server/danim/src/main/java/project/danim/member/repository/MemberRepository.java
  server/danim/src/main/java/project/danim/member/service/MemberMap.java
  server/danim/src/main/java/project/danim/member/service/MemberQueries.java
  server/danim/src/main/java/project/danim/member/service/MemberService.java
  server/danim/src/main/java/project/danim/security/config/SecurityConfig.java
Labels: BE

#118 [BE] AWS 이미지 업로드 구현 완료
  server/danim/src/main/java/project/danim/S3/S3Controller.java
  server/danim/src/main/java/project/danim/S3/S3Service.java
  server/danim/src/main/java/project/danim/config/AwsS3Config.java
  server/danim/src/main/java/project/danim/image/AwsS3Controller.java
  server/danim/src/main/java/project/danim/image/AwsS3Service.java
  server/danim/src/main/java/project/danim/reply/controller/ReplyController.java
  server/danim/src/main/java/project/danim/tag/dto/TagPostDto.java
  server/danim/src/main/resources/application.yml
Labels: feature, BE 김은진, chore
